CREATE or replace MATERIALIZED EXTERNAL TABLE "DEMO_Vaccine_Distro"."airport_routes"
(
   "EDGE_ID" INTEGER NOT NULL,
   "EDGE_NODE1_ID" INTEGER NOT NULL,
   "EDGE_NODE2_ID" INTEGER NOT NULL,
   "EDGE_WKTLINE" GEOMETRY NOT NULL,
   "EDGE_NODE1_X" DOUBLE NOT NULL,
   "EDGE_NODE1_Y" DOUBLE NOT NULL,
   "EDGE_NODE2_X" DOUBLE NOT NULL,
   "EDGE_NODE2_Y" DOUBLE NOT NULL,
   "EDGE_NODE1_WKTPOINT" GEOMETRY NOT NULL,
   "EDGE_NODE2_WKTPOINT" GEOMETRY NOT NULL,
   "EDGE_NODE1_NAME" VARCHAR (128, dict) NOT NULL,
   "EDGE_NODE2_NAME" VARCHAR (128, dict) NOT NULL,
   "EDGE_DIRECTION" INTEGER NOT NULL,
   "EDGE_LABEL" VARCHAR (32) NOT NULL,
   "EDGE_WEIGHT_VALUESPECIFIED" DOUBLE NOT NULL
)
FILE PATHS '/mnt/data/persist/out_edges.csv'
FORMAT DELIMITED TEXT;