CREATE OR REPLACE MATERIALIZED EXTERNAL TABLE "DEMO_Vaccine_Distro"."vaccine_utilization_usa"
(
   "State_Territory_Federal_Entity" VARCHAR (32),
   "Total_Doses_Delivered" INTEGER,
   "Doses_Delivered_per_100K" INTEGER,
   "18plus_Doses_Delivered_per_100K" INTEGER,
   "Total_Doses_Administered_by_State_where_Administered" INTEGER,
   "Doses_Administered_per_100k_by_State_where_Administered" INTEGER,
   "18plus_Doses_Administered_by_State_where_Administered" INTEGER,
   "18plus_Doses_Administered_per_100K_by_State_where_Administered" INTEGER,
   "People_with_at_least_One_Dose_by_State_of_Residence" INTEGER,
   "Percent_of_Total_Pop_with_at_least_One_Dose_by_State_of_Residence" DECIMAL(18,4),
   "People_18plus_with_at_least_One_Dose_by_State_of_Residence" INTEGER,
   "Percent_of_18plus_Pop_with_at_least_One_Dose_by_State_of_Residence" DECIMAL(18,4),
   "People_Fully_Vaccinated_by_State_of_Residence" INTEGER,
   "Percent_of_Total_Pop_Fully_Vaccinated_by_State_of_Residence" DECIMAL(18,4),
   "People_18plus_Fully_Vaccinated_by_State_of_Residence" INTEGER,
   "Percent_of_18plus_Pop_Fully_Vaccinated_by_State_of_Residence" DECIMAL(18,4),
   "Total_Number_of_Pfizer_doses_delivered" INTEGER,
   "Total_Number_of_Moderna_doses_delivered" INTEGER,
   "Total_Number_of_Janssen_doses_delivered" INTEGER,
   "Total_Number_of_doses_from_unknown_manufacturer_delivered" TINYINT,
   "Total_Number_of_Janssen_doses_administered" INTEGER,
   "Total_Number_of_Moderna_doses_administered" INTEGER,
   "Total_Number_of_Pfizer_doses_adminstered" INTEGER,
   "Total_Number_of_doses_from_unknown_manufacturer_administered" INTEGER,
   "People_Fully_Vaccinated_Moderna_Resident" INTEGER,
   "People_Fully_Vaccinated_Pfizer_Resident" INTEGER,
   "People_Fully_Vaccinated_Janssen_Resident" INTEGER,
   "People_Fully_Vaccinated_Unknown_2_dose_manufacturer_Resident" SMALLINT,
   "People_18plus_Fully_Vaccinated_Moderna_Resident" INTEGER,
   "People_18plus_Fully_Vaccinated_Pfizer_Resident" INTEGER,
   "People_18plus_Fully_Vaccinated_Janssen_Resident" INTEGER,
   "People_18plus_Fully_Vaccinated_Unknown_2_dose_manufacturer_Resident" SMALLINT,
   "People_with_2_Doses_by_State_of_Residence" INTEGER,
   "Percent_of_Total_Pop_with_1plus_Doses_by_State_of_Residence" DECIMAL(18,4),
   "People_18plus_with_1plus_Doses_by_State_of_Residence" INTEGER,
   "Percent_of_18plus_Pop_with_1plus_Doses_by_State_of_Residence" DECIMAL(18,4),
   "Percent_of_Total_Pop_with_2_Doses_by_State_of_Residence" DECIMAL(18,4),
   "People_18plus_with_2_Doses_by_State_of_Residence" INTEGER,
   "Percent_of_18plus_Pop_with_2_Doses_by_State_of_Residence" DECIMAL(18,4),
   "People_with_1plus_Doses_by_State_of_Residence" INTEGER,
   "People_65plus_with_at_least_One_Dose_by_State_of_Residence" INTEGER,
   "Percent_of_65plus_Pop_with_at_least_One_Dose_by_State_of_Residence" DECIMAL(18,4),
   "People_65plus_Fully_Vaccinated_by_State_of_Residence" INTEGER,
   "Percent_of_65plus_Pop_Fully_Vaccinated_by_State_of_Residence" DECIMAL(18,4),
   "People_65plus_Fully_Vaccinated_Moderna_Resident" INTEGER,
   "People_65plus_Fully_Vaccinated_Pfizer_Resident" INTEGER,
   "People_65plus_Fully_Vaccinated_Janssen_Resident" INTEGER,
   "People_65plus_Fully_Vaccinated_Unknown_2_dose_Manuf_Resident" SMALLINT,
   "65plus_Doses_Administered_by_State_where_Administered" INTEGER,
   "Doses_Administered_per_100k_of_65plus_pop_by_State_where_Administered" INTEGER,
   "Doses_Delivered_per_100k_of_65plus_pop" INTEGER,
   "People_12plus_with_at_least_One_Dose_by_State_of_Residence" INTEGER,
   "Percent_of_12plus_Pop_with_at_least_One_Dose_by_State_of_Residence" DECIMAL(18,4),
   "People_12plus_Fully_Vaccinated_by_State_of_Residence" INTEGER,
   "Percent_of_12plus_Pop_Fully_Vaccinated_by_State_of_Residence" DECIMAL(18,4),
   "People_12plus_Fully_Vaccinated_Moderna_Resident" INTEGER,
   "People_12plus_Fully_Vaccinated_Pfizer_Resident" INTEGER,
   "People_12plus_Fully_Vaccinated_Janssen_Resident" INTEGER,
   "People_12plus_Fully_Vaccinated_Unknown_2_dose_Manuf_Resident" SMALLINT,
   "12plus_Doses_Administered_by_State_where_Administered" INTEGER,
   "Doses_Administered_per_100k_of_12plus_pop_by_State_where_Administered" INTEGER,
   "Doses_Delivered_per_100k_of_12plus_pop" INTEGER
)
FILE PATHS '/mnt/data/persist/supply.csv'
FORMAT DELIMITED TEXT; 