CREATE MATERIALIZED EXTERNAL TABLE "DEMO_Vaccine_Distro"."global_covid_statistics"
(
   "iso_code" VARCHAR (8, dict) NOT NULL,
   "continent" VARCHAR (16, dict),
   "location" VARCHAR (32, dict) NOT NULL,
   "date" DATE (dict) NOT NULL,
   "total_cases" DECIMAL(18,4),
   "new_cases" DECIMAL(18,4),
   "new_cases_smoothed" DECIMAL(18,4),
   "total_deaths" DECIMAL(18,4),
   "new_deaths" DECIMAL(18,4),
   "new_deaths_smoothed" DECIMAL(18,4),
   "total_cases_per_million" DECIMAL(18,4),
   "new_cases_per_million" DECIMAL(18,4),
   "new_cases_smoothed_per_million" DECIMAL(18,4),
   "total_deaths_per_million" DECIMAL(18,4),
   "new_deaths_per_million" DECIMAL(18,4),
   "new_deaths_smoothed_per_million" DECIMAL(18,4),
   "reproduction_rate" DECIMAL(18,4),
   "icu_patients" DECIMAL(18,4),
   "icu_patients_per_million" DECIMAL(18,4),
   "hosp_patients" DECIMAL(18,4),
   "hosp_patients_per_million" DECIMAL(18,4),
   "weekly_icu_admissions" DECIMAL(18,4),
   "weekly_icu_admissions_per_million" DECIMAL(18,4),
   "weekly_hosp_admissions" DECIMAL(18,4),
   "weekly_hosp_admissions_per_million" DECIMAL(18,4),
   "new_tests" DECIMAL(18,4),
   "total_tests" DECIMAL(18,4),
   "total_tests_per_thousand" DECIMAL(18,4),
   "new_tests_per_thousand" DECIMAL(18,4),
   "new_tests_smoothed" DECIMAL(18,4),
   "new_tests_smoothed_per_thousand" DECIMAL(18,4),
   "positive_rate" DECIMAL(18,4),
   "tests_per_case" DECIMAL(18,4),
   "tests_units" VARCHAR (16, dict),
   "total_vaccinations" DECIMAL(18,4),
   "people_vaccinated" DECIMAL(18,4),
   "people_fully_vaccinated" DECIMAL(18,4),
   "new_vaccinations" DECIMAL(18,4),
   "new_vaccinations_smoothed" DECIMAL(18,4),
   "total_vaccinations_per_hundred" DECIMAL(18,4),
   "people_vaccinated_per_hundred" DECIMAL(18,4),
   "people_fully_vaccinated_per_hundred" DECIMAL(18,4),
   "new_vaccinations_smoothed_per_million" DECIMAL(18,4),
   "stringency_index" DECIMAL(18,4),
   "population" DECIMAL(18,4),
   "population_density" DECIMAL(18,4),
   "median_age" DECIMAL(18,4),
   "aged_65_older" DECIMAL(18,4),
   "aged_70_older" DECIMAL(18,4),
   "gdp_per_capita" DECIMAL(18,4),
   "extreme_poverty" DECIMAL(18,4),
   "cardiovasc_death_rate" DECIMAL(18,4),
   "diabetes_prevalence" DECIMAL(18,4),
   "female_smokers" DECIMAL(18,4),
   "male_smokers" DECIMAL(18,4),
   "handwashing_facilities" DECIMAL(18,4),
   "hospital_beds_per_thousand" DECIMAL(18,4),
   "life_expectancy" DECIMAL(18,4),
   "human_development_index" DECIMAL(18,4),
   "excess_mortality" DECIMAL(18,4)
)
FILE PATHS '/mnt/data/persist/owid-covid-data.csv'
FORMAT DELIMITED TEXT; 