CREATE OR REPLACE MATERIALIZED EXTERNAL TABLE "DEMO_Vaccine_Distro"."airport_nodes"
(
   "NODE_ID" SMALLINT NOT NULL,
   "NODE_X" DOUBLE NOT NULL,
   "NODE_Y" DOUBLE NOT NULL,
   "NODE_NAME" VARCHAR (128) NOT NULL,
   "NODE_WKTPOINT" GEOMETRY NOT NULL,
   "NODE_LABEL" VARCHAR (128) NOT NULL,
   "IATA" VARCHAR (4) NOT NULL,
   "ICAO" VARCHAR (4) NOT NULL,
   "CITY" VARCHAR (64),
   "COUNTRY" VARCHAR (32, dict) NOT NULL
)
FILE PATHS '/mnt/data/persist/out_nodes.csv'
FORMAT DELIMITED TEXT;